import streamlit as st
import pandas as pd
from datetime import datetime
from fpdf import FPDF
import qrcode
import tempfile
import os
import time

# Importujemy narzędzie do czyszczenia danych z naszego pliku utils.py
from utils import clean_for_gsheets

# ==========================================
# 1. FUNKCJE POMOCNICZE DLA PDF
# ==========================================
def pdf_sanitize(text):
    """Usuwa polskie znaki, by uniknąć błędów kodowania w FPDF"""
    text = str(text)
    replacements = {
        'ą':'a', 'ć':'c', 'ę':'e', 'ł':'l', 'ń':'n', 'ó':'o', 'ś':'s', 'ź':'z', 'ż':'z', 
        'Ą':'A', 'Ć':'C', 'Ę':'E', 'Ł':'L', 'Ń':'N', 'Ó':'O', 'Ś':'S', 'Ź':'Z', 'Ż':'Z', 
        '€':'EUR', '–':'-', '—':'-', '”':'"', '„':'"', '’':"'", '“':'"', '\xa0':' '
    }
    for pl, eng in replacements.items(): 
        text = text.replace(pl, eng)
    return text.encode('latin-1', 'ignore').decode('latin-1')

# ==========================================
# 2. SILNIK GENERUJĄCY DOKUMENT (FPDF)
# ==========================================
class PRO_TransportOrder(FPDF):
    def __init__(self, watermark_text="SQM", opiekun="PD"):
        super().__init__()
        self.watermark_text = pdf_sanitize(watermark_text)
        self.opiekun = opiekun
        
    def add_watermark(self):
        self.set_font("Arial", 'B', 45)
        self.set_text_color(245, 245, 245) 
        for j in range(80, 297, 45):
            przesuniecie = 35 if (j // 45) % 2 == 0 else 0
            for i in range(-20, 210, 70): 
                self.text(i + przesuniecie, j, self.watermark_text)
        self.set_text_color(0, 0, 0)
        
    def header(self):
        # Automatyczne zaciąganie logo (szuka pliku logosqm.jpg lub .png w głównym folderze)
        try:
            if os.path.exists("logosqm.png"): 
                self.image("logosqm.png", 10, 8, 50)
            elif os.path.exists("logosqm.jpg"): 
                self.image("logosqm.jpg", 10, 8, 50)
        except Exception as e:
            pass
            
        self.set_font("Arial", 'B', 18)
        self.set_text_color(40, 40, 40)
        self.set_xy(65, 12)
        self.cell(105, 8, pdf_sanitize("TRANSPORT ORDER"), ln=True, align='R')
        
        self.set_font("Arial", 'B', 11)
        self.set_text_color(100, 100, 100)
        self.set_xy(65, 20)
        self.cell(105, 5, pdf_sanitize("ZLECENIE TRANSPORTOWE"), ln=True, align='R')
        
        self.set_font("Arial", '', 8)
        self.set_xy(65, 26)
        self.cell(105, 5, pdf_sanitize("Logistics Department"), ln=True, align='R')
        self.ln(15)
        
    def footer(self):
        self.set_y(-30)
        self.set_font("Arial", 'I', 10)
        self.set_text_color(25, 118, 210)
        self.cell(0, 5, pdf_sanitize("Thank you for your cooperation! / Dziękujemy za współpracę!"), ln=True, align='C')
        
        self.set_font("Arial", '', 8)
        self.set_text_color(100, 100, 100)
        email = "logistics@company.com" if self.opiekun == "PD" else "transport@company.com"
        self.cell(0, 5, pdf_sanitize(f"Generated by Global Logistics Terminal | {email}"), ln=True, align='C')

def generate_pro_pdf(dane):
    pdf = PRO_TransportOrder(opiekun=dane.get('opiekun', 'PD'))
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.add_watermark()
    
    # Generowanie kodu QR dla zlecenia
    qr = qrcode.QRCode(version=1, box_size=10, border=1)
    qr.add_data(f"VERIFY: {dane['nr']}\nSYS: TERMINAL PRO")
    qr.make(fit=True)
    img_qr = qr.make_image(fill_color="black", back_color="white")
    with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp:
        img_qr.save(tmp, format="PNG")
        qr_path = tmp.name
        
    pdf.image(qr_path, 175, 10, 25)
    if os.path.exists(qr_path): 
        os.remove(qr_path)
        
    # Pasek z numerem zlecenia i datą
    pdf.set_xy(10, 40)
    pdf.set_font("Arial", 'B', 9)
    pdf.set_fill_color(25, 118, 210)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(25, 8, pdf_sanitize(" REF "), border=0, fill=True, align='C')
    
    pdf.set_fill_color(245, 245, 245)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(60, 8, pdf_sanitize(f" {dane['nr']}"), border=0, fill=True)
    pdf.cell(5, 8, "", border=0) 
    
    pdf.set_fill_color(25, 118, 210)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(25, 8, pdf_sanitize(" DATE "), border=0, fill=True, align='C')
    
    pdf.set_fill_color(245, 245, 245)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(60, 8, pdf_sanitize(f" {datetime.now().strftime('%d.%m.%Y')}"), border=0, fill=True)
    pdf.ln(12)

    def draw_section_header(num, title):
        pdf.set_fill_color(25, 118, 210)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(10, 10, pdf_sanitize(str(num).zfill(2)), fill=True, align='C')
        pdf.set_text_color(40, 40, 40)
        pdf.cell(5, 10, "", border=0)
        pdf.cell(0, 10, pdf_sanitize(title), ln=True)
        pdf.ln(2)

    def draw_row(label, val, border_b=True):
        x_start, y_start = pdf.get_x(), pdf.get_y()
        pdf.set_font("Arial", 'B', 8)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(65, 6, pdf_sanitize(label), border=0)
        
        pdf.set_font("Arial", 'B', 10)
        pdf.set_text_color(40, 40, 40)
        pdf.set_xy(x_start + 65, y_start + 0.5)
        pdf.multi_cell(125, 5, pdf_sanitize(val), border=0)
        y_end = pdf.get_y() + 1.5
        
        if border_b: 
            pdf.set_draw_color(230, 230, 230)
            pdf.line(10, y_end, 200, y_end)
        pdf.set_xy(10, y_end + 2)

    # Sekcja 1
    draw_section_header(1, "PARTIES & ASSETS / STRONY I POJAZD")
    draw_row("CONTRACTOR / PRZEWOŹNIK:", dane['przewoznik_detale'])
    draw_row("VEHICLE & DRIVER / AUTO I KIEROWCA:", dane['auto'] if dane['auto'] else "TBA / Do podania")
    draw_row("VALUATION MODEL / TRYB WYCENY:", dane['typ_zlecenia'], border_b=False)
    pdf.ln(4)

    # Sekcja 2
    draw_section_header(2, "LOGISTICS TIMELINE / HARMONOGRAM")
    draw_row("LOADING PLACE / MIEJSCE ZAŁADUNKU:", dane['zaladunek'])
    draw_row("LOADING DATE / DATA ZAŁADUNKU:", dane['data_zal'])
    draw_row("UNLOADING PLACE / MIEJSCE ROZŁADUNKU:", dane['rozladunek'])
    if dane['typ_zlecenia'] == "Pełny event":
        draw_row("UNLOADING DATE / DATA ROZŁADUNKU:", dane['data_roz'])
        draw_row("EMPTIES IN / ODBIÓR PUSTYCH:", dane['data_emp_in'])
        draw_row("RETURN LOAD / DATA POWROTU:", dane['data_emp_out'], border_b=False)
    else: 
        draw_row("UNLOADING DATE / DATA ROZŁADUNKU:", dane['data_roz'], border_b=False)
    pdf.ln(4)

    # Sekcja 3
    draw_section_header(3, "FINANCIALS & CARGO / FINANSE I ŁADUNEK")
    sy = pdf.get_y()
    
    pdf.set_xy(120, sy)
    pdf.set_fill_color(25, 118, 210)
    pdf.rect(120, sy, 80, 25, 'F')
    
    pdf.set_xy(125, sy + 3)
    pdf.set_font("Arial", 'B', 8)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(70, 5, pdf_sanitize("TOTAL NET RATE / KWOTA NETTO"), ln=True)
    
    pdf.set_xy(125, sy + 10)
    pdf.set_font("Arial", 'B', 20)
    pdf.cell(70, 10, pdf_sanitize(f"{dane['stawka']} {dane['waluta']}"), ln=True)
    
    pdf.set_xy(10, sy)
    pdf.set_font("Arial", 'B', 8)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(55, 5, pdf_sanitize("CARGO TYPE / TOWAR:"), border=0)
    
    pdf.set_font("Arial", 'B', 10)
    pdf.set_text_color(40, 40, 40)
    pdf.set_xy(65, sy)
    pdf.multi_cell(50, 5, pdf_sanitize("Exhibition Structures / AV Equipment"))
    
    pdf.set_xy(10, pdf.get_y() + 2)
    pdf.set_font("Arial", 'B', 8)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(55, 5, pdf_sanitize("GROSS WEIGHT / WAGA BRUTTO:"), border=0)
    
    pdf.set_font("Arial", 'B', 10)
    pdf.set_text_color(40, 40, 40)
    pdf.set_xy(65, pdf.get_y())
    pdf.cell(50, 5, pdf_sanitize(f"{dane['waga']} kg"))
    
    # Sekcja 4
    pdf.set_xy(10, sy + 35)
    draw_section_header(4, "SPECIAL PROVISIONS / UWAGI SPECJALNE")
    pdf.set_font("Arial", 'I', 10)
    pdf.multi_cell(0, 6, pdf_sanitize(dane['uwagi']))

    return bytes(pdf.output(dest='S').encode('latin1'))

# ==========================================
# 3. INTERFEJS UŻYTKOWNIKA (UI) KREATORA
# ==========================================
def render_kreator(conn, df_zlecenia, df_schedule, df_miejsca, df_carriers):
    
    # Zwróć uwagę na płaski kod HTML (bez wcięć), by Streamlit renderował to jako baner
    st.markdown("""<div class="aviation-banner" style="background: linear-gradient(135deg, #1E293B 0%, #334155 100%); border-left: 8px solid #38BDF8;">
<h1 style="color:white;">📄 KREATOR ZLECEŃ PRO v5.4</h1>
<p style="color:#CBD5E1;">Zautomatyzowane generowanie zasileń PDF i rejestracja w bazie Zlecenia.</p>
</div>""", unsafe_allow_html=True)
    
    # Zabezpieczenie przed "znikaniem" pliku po kliknięciu
    if "pdf_data" in st.session_state:
        st.success(f"✅ Zlecenie {st.session_state.get('pdf_nr', '')} zapisane bezpiecznie w bazie!")
        st.download_button("📥 POBIERZ DOKUMENT PDF", data=st.session_state["pdf_data"], file_name=st.session_state["pdf_name"], mime="application/pdf", use_container_width=True)
        st.markdown("<br>", unsafe_allow_html=True)
        if st.button("🔄 ZAMKNIJ I WRÓĆ DO KREATORA", use_container_width=True):
            del st.session_state["pdf_data"]
            st.rerun()
            
    else:
        tryb_pracy = st.radio("Tryb działania kreatora:", ["Nowe Zlecenie", "Edycja Istniejącego Zlecenia"], horizontal=True)
        
        # Wartości domyślne dla formularza
        val_typ_zlecenia = "Tylko dostawa"
        val_waga = 1000
        val_data_zal = datetime.now().date()
        val_data_roz = datetime.now().date()
        val_data_emp_in = datetime.now().date()
        val_data_emp_out = datetime.now().date()
        val_nazwa_przewoznika = "Wybierz..."
        val_detale_przewoznika = ""
        val_stawka_final = 0.0
        val_waluta = "EUR"
        val_z_sel = "Magazyn SQM Komorniki"
        val_z_man = ""
        val_c_auto = ""
        val_instrukcje = "Parking strzeżony, pasy zabezpieczające; załadować po długości, casy nie mogą leżeć."
        val_podpis = "PD"
        val_wartosc_towaru = 100000
        val_projekt = "Brak"
        wybrane_zlecenie_nr = None
        gs_row_index = None
        val_zrodlo = "Przewoźnik z bazy"
        
        lista_eventow = df_schedule['Event'].dropna().unique().tolist() if not df_schedule.empty else []
        lista_miejsc_baza = df_miejsca['Nazwa do listy'].tolist() if not df_miejsca.empty else []
        opcje_lokalizacji = ["Magazyn SQM Komorniki"] + lista_miejsc_baza + ["INNE (wpisz ręcznie)"]
        
        if tryb_pracy == "Edycja Istniejącego Zlecenia":
            if df_zlecenia.empty or len(df_zlecenia[df_zlecenia['Numer zlecenia'].str.strip() != ""]) == 0:
                st.warning("Baza zleceń jest pusta - brak danych do edycji.")
                st.stop()
            else:
                lista_nr = df_zlecenia[df_zlecenia['Numer zlecenia'].str.strip() != ""]['Numer zlecenia'].tolist()
                wybrane_zlecenie_nr = st.selectbox("🎯 Wybierz numer zlecenia do edycji:", lista_nr)
                idx_pd = df_zlecenia[df_zlecenia['Numer zlecenia'] == wybrane_zlecenie_nr].index[0]
                r_edit = df_zlecenia.iloc[idx_pd]
                gs_row_index = int(idx_pd) + 2 
                
                val_typ_zlecenia = "Pełny event" if "TARGI" in str(r_edit.get('Typ', '')) or "CYKL:" in str(r_edit.get('Uwagi / Instrukcje', '')) else "Tylko dostawa"
                
                try: 
                    val_data_zal = datetime.strptime(str(r_edit.get('Data załadunku', '')), "%Y-%m-%d").date()
                except: pass
                    
                try: 
                    val_data_roz = datetime.strptime(str(r_edit.get('Data rozładunku', '')), "%Y-%m-%d").date()
                except: pass
                
                stawka_str = str(r_edit.get('Stawka', '0 EUR'))
                if " " in stawka_str:
                    try: 
                        val_stawka_final = float(stawka_str.split(" ")[0])
                        val_waluta = stawka_str.split(" ")[1]
                    except: pass
                else:
                    try: 
                        val_stawka_final = float(stawka_str)
                    except: pass
                    
                val_nazwa_przewoznika = str(r_edit.get('Zleceniobiorca', ''))
                val_projekt = str(r_edit.get('ID Projektu', ''))
                val_z_sel = str(r_edit.get('Miejsce Zaladunku', ''))
                
                uwagi_baza = str(r_edit.get('Uwagi / Instrukcje', ''))
                if "AUTO: " in uwagi_baza:
                    try: 
                        val_c_auto = uwagi_baza.split("AUTO: ")[1].split(" ||")[0]
                    except: pass
                
                # Zabezpieczenie EUR/PLN z przeszlosci
                if "WART: " in uwagi_baza:
                    try: 
                        val_wartosc_towaru = int(uwagi_baza.split("WART: ")[1].split(" EUR")[0])
                    except: 
                        try: 
                            val_wartosc_towaru = int(uwagi_baza.split("WART: ")[1].split(" PLN")[0])
                        except: pass
                        
                if " || " in uwagi_baza:
                    parts = uwagi_baza.split(" || ")
                    if len(parts) >= 4: 
                        val_instrukcje = parts[3]
                    elif len(parts) == 3 and "CYKL:" not in parts[2]: 
                        val_instrukcje = parts[2]
                
                # Sprawdzenie zrodla przewoznika
                r_p = df_carriers[df_carriers['Firma'] == val_nazwa_przewoznika]
                if not r_p.empty:
                    r = r_p.iloc[0]
                    val_detale_przewoznika = f"{str(r.get('Firma', ''))}\n{str(r.get('Adres', ''))}\nNIP: {str(r.get('NIP', ''))}\nTel: {str(r.get('Telefon', ''))} | {str(r.get('Kontakt', ''))}".strip()
                    val_zrodlo = "Przewoźnik z bazy"
                else:
                    val_zrodlo = "Przewoźnik z giełdy"
                    val_detale_przewoznika = ""

        with st.container(border=True):
            st.markdown("#### 1. Kierunek i Harmonogram")
            typ_zlecenia = st.radio("Tryb operacji:", ["Tylko dostawa", "Pełny event"], index=["Tylko dostawa", "Pełny event"].index(val_typ_zlecenia), horizontal=True)
            waga = st.number_input("Waga (kg):", min_value=100, step=100, value=val_waga)
            
            d1, d2 = st.columns(2)
            data_zal = d1.date_input("Data załadunku (PL):", val_data_zal)
            data_roz = d2.date_input("Data rozładunku (Cel):", val_data_roz)
            
            if typ_zlecenia == "Pełny event":
                h1, h2 = st.columns(2)
                data_emp_in = h1.date_input("Odbiór pustych:", val_data_emp_in)
                data_emp_out = h2.date_input("Powrót / Załadunek:", val_data_emp_out)
            else: 
                data_emp_in, data_emp_out = "", ""

        with st.container(border=True):
            st.markdown("#### 2. Przewoźnik i Koszty")
            zrodlo_idx = ["Przewoźnik z bazy", "Przewoźnik z giełdy"].index(val_zrodlo) if val_zrodlo in ["Przewoźnik z bazy", "Przewoźnik z giełdy"] else 0
            zrodlo = st.radio("Źródło przewoźnika:", ["Przewoźnik z bazy", "Przewoźnik z giełdy"], index=zrodlo_idx, horizontal=True)
            
            lista_cennikowa = df_carriers['Firma'].dropna().unique().tolist() if not df_carriers.empty else []
            
            if zrodlo == "Przewoźnik z bazy":
                if tryb_pracy == "Edycja Istniejącego Zlecenia" and val_nazwa_przewoznika not in lista_cennikowa and val_nazwa_przewoznika != "":
                    lista_cennikowa.append(val_nazwa_przewoznika)
                
                f1, f2, f3 = st.columns([2, 1, 1])
                nazwa_przewoznika = f1.selectbox("Wybierz partnera z bazy:", ["Wybierz..."] + lista_cennikowa, index=(lista_cennikowa.index(val_nazwa_przewoznika)+1 if val_nazwa_przewoznika in lista_cennikowa else 0))
                
                if nazwa_przewoznika != "Wybierz...":
                    r_p = df_carriers[df_carriers['Firma'] == nazwa_przewoznika]
                    if not r_p.empty:
                        r = r_p.iloc[0]
                        detale_przewoznika = f"{str(r.get('Firma', ''))}\n{str(r.get('Adres', ''))}\nNIP: {str(r.get('NIP', ''))}\nTel: {str(r.get('Telefon', ''))} | {str(r.get('Kontakt', ''))}".strip()
                    else: 
                        detale_przewoznika = nazwa_przewoznika
                else: 
                    detale_przewoznika = ""
                
                stawka_final = f2.number_input("Cena Total:", value=float(val_stawka_final))
                waluta = f3.selectbox("Waluta:", ["EUR", "PLN"], index=(["EUR", "PLN"].index(val_waluta) if val_waluta in ["EUR", "PLN"] else 0))
                
            else:
                nazwa_przewoznika = st.text_input("Nazwa firmy z giełdy:", value=val_nazwa_przewoznika if val_zrodlo == "Przewoźnik z giełdy" else "")
                detale_przewoznika = st.text_area("Pełne dane (Adres, NIP, Kontakt):", value=val_detale_przewoznika if val_zrodlo == "Przewoźnik z giełdy" else "", placeholder="Wklej pełne dane przewoźnika do zamówienia...")
                f1, f2 = st.columns(2)
                stawka_final = f1.number_input("Cena Total:", value=float(val_stawka_final))
                waluta = f2.selectbox("Waluta:", ["EUR", "PLN"], index=(["EUR", "PLN"].index(val_waluta) if val_waluta in ["EUR", "PLN"] else 0))

        with st.container(border=True):
            st.markdown("#### 3. Logistyka Miejsc")
            projekt = st.selectbox("Przypisz do Projektu:", ["Brak"] + lista_eventow, index=(lista_eventow.index(val_projekt)+1 if val_projekt in lista_eventow else 0))
            l1, l2 = st.columns(2)
            
            with l1:
                z_sel = st.selectbox("Miejsce startu:", opcje_lokalizacji, index=(opcje_lokalizacji.index(val_z_sel) if val_z_sel in opcje_lokalizacji else 0))
                z_man = st.text_input("Adres startu (ręcznie):", value=val_z_man) if z_sel == "INNE (wpisz ręcznie)" else ""
            with l2:
                r_s = st.selectbox("Miejsce celu:", opcje_lokalizacji)
                r_m = st.text_input("Adres celu (ręcznie):") if r_s == "INNE (wpisz ręcznie)" else ""

        with st.container(border=True):
            st.markdown("#### 4. Realizacja i Uwagi")
            d_auto, d_wart = st.columns(2)
            c_auto = d_auto.text_input("Auto / Kierowca:", value=val_c_auto, placeholder="np. PO 12345 / Jan Kowalski")
            wartosc_towaru = d_wart.number_input("Wartość towaru (EUR):", min_value=0, value=val_wartosc_towaru)
            
            u1, u2 = st.columns([3, 1])
            instrukcje = u1.text_area("Instrukcje dodatkowe:", value=val_instrukcje, height=80)
            podpis = u2.radio("Podpis:", ["PD", "PK"], index=(["PD", "PK"].index(val_podpis) if val_podpis in ["PD", "PK"] else 0), horizontal=True)

        btn_label = "⚡ ZAPISZ ZMIANY I REGENERUJ PDF" if tryb_pracy == "Edycja Istniejącego Zlecenia" else "⚡ GENERUJ I ZAPISZ ZLECENIE PRO"

        if st.button(btn_label, type="primary", use_container_width=True):
            if not nazwa_przewoznika or nazwa_przewoznika == "Wybierz...":
                st.error("Podaj nazwę przewoźnika!")
            else:
                with st.spinner("Przetwarzanie dokumentów i zapis do bazy..."):
                    try:
                        final_zal_db = z_man if z_sel == "INNE (wpisz ręcznie)" else z_sel
                        final_roz_db = r_m if r_s == "INNE (wpisz ręcznie)" else r_s
                        
                        def build_full_address(place_name, manual_addr, df):
                            if place_name == "INNE (wpisz ręcznie)": 
                                return manual_addr
                            if place_name == "Magazyn SQM Komorniki": 
                                return "Magazyn Centralny;\nul. Poznańska 165, Komorniki"
                            if df is not None and not df.empty:
                                row = df[df['Nazwa do listy'] == place_name]
                                if not row.empty:
                                    r = row.iloc[0]
                                    return f"{r.get('Nazwa pełna / Firma', place_name)}\n{r.get('Ulica i numer', '')}\n{r.get('Kod pocztowy', '')} {r.get('Miasto', '')}, {r.get('Kraj', '')}"
                            return place_name

                        full_zal_pdf = build_full_address(z_sel, z_man, df_miejsca)
                        full_roz_pdf = build_full_address(r_s, r_m, df_miejsca)
                        
                        historia_cyklu = f"CYKL: {data_zal} -> {data_roz}" + (f" | EMP: {data_emp_in} | POWRÓT: {data_emp_out}" if typ_zlecenia == "Pełny event" else "")
                        pelne_uwagi_db = f"AUTO: {c_auto} || WART: {wartosc_towaru} EUR || {historia_cyklu} || {instrukcje}"
                        uwagi_na_pdf = f"VEHICLE/DRIVER: {c_auto}\n{instrukcje}"
                        
                        if tryb_pracy == "Edycja Istniejącego Zlecenia":
                            nr_zlecenia = wybrane_zlecenie_nr
                        else:
                            dzis_ile = len(df_zlecenia[df_zlecenia['Numer zlecenia'].str.contains(datetime.now().strftime('%y/%m%d'))]) if not df_zlecenia.empty else 0
                            idx_nowy = dzis_ile + 1
                            nr_zlecenia = f"CRG{datetime.now().strftime('%y/%m%d')}/{podpis}{idx_nowy:02d}"
                        
                        paczka_pdf = {
                            "typ_zlecenia": typ_zlecenia, 
                            "nr": nr_zlecenia, 
                            "przewoznik_nazwa": nazwa_przewoznika, 
                            "przewoznik_detale": detale_przewoznika,
                            "stawka": stawka_final, 
                            "waluta": waluta, 
                            "zaladunek": full_zal_pdf, 
                            "data_zal": str(data_zal),
                            "rozladunek": full_roz_pdf, 
                            "data_roz": str(data_roz), 
                            "data_emp_in": str(data_emp_in), 
                            "data_emp_out": str(data_emp_out),
                            "waga": waga, 
                            "auto": c_auto, 
                            "uwagi": uwagi_na_pdf, 
                            "opiekun": podpis 
                        }
                        
                        nowy_wiersz = pd.DataFrame([{
                            "Data": datetime.now().strftime("%Y-%m-%d %H:%M"), 
                            "Numer zlecenia": nr_zlecenia, 
                            "Dział": "LOGISTYKA CARGO", 
                            "Zleceniobiorca": nazwa_przewoznika,
                            "Miejsce Zaladunku": final_zal_db, 
                            "Miejsce Rozladunku": final_roz_db, 
                            "Data załadunku": str(data_zal), 
                            "Data rozładunku": str(data_roz),
                            "Typ": "Zabudowa Targowa PRO", 
                            "Puste1": "", "Puste2": "", "Puste3": "", "Puste4": "", 
                            "Uwagi / Instrukcje": pelne_uwagi_db, 
                            "Puste5": "", 
                            "ID Projektu": projekt, 
                            "Rodzaj": "TARGI", 
                            "Stawka": f"{stawka_final} {waluta}"
                        }])
                        
                        if tryb_pracy == "Edycja Istniejącego Zlecenia":
                            df_zlecenia.iloc[idx_pd] = nowy_wiersz.iloc[0]
                            conn.update(worksheet="Zlecenia", data=clean_for_gsheets(df_zlecenia))
                        else:
                            conn.update(worksheet="Zlecenia", data=clean_for_gsheets(pd.concat([df_zlecenia, nowy_wiersz], ignore_index=True)))
                            
                        # Bezpieczna pauza dla API Google Sheets
                        time.sleep(1.5) 
                        
                        # Zapis danych PDF do stanu sesji
                        pdf_bytes = generate_pro_pdf(paczka_pdf)
                        st.session_state["pdf_data"] = pdf_bytes
                        st.session_state["pdf_name"] = f"Order_{nr_zlecenia.replace('/', '_')}.pdf"
                        st.session_state["pdf_nr"] = nr_zlecenia
                        
                        st.cache_data.clear()
                        st.rerun()
                        
                    except Exception as e:
                        st.error(f"⚠️ Wystąpił błąd podczas generowania i zapisu: {e}")
